products/urls.py
from django.urls import path
from .views import ProductDetailView, ProductView, order, get_started, eportal, it_view, it_success, application_view, it_manual_view, product_success_view

app_name = 'wholphinplus'

urlpatterns = [
    path('', ProductView.as_view(), name='products'),
    path('<int:pk>/', ProductDetailView.as_view(), name='productdetail'),
    path('order/', order, name='order'),
    path('get{}started/', get_started, name='get started'),
    path('eportal/', eportal, name='eportal'),
    path('it1/', it_view, name='it1'),
    path('it1l/', it_manual_view, name='it1l'),
    path('it_success/', it_success, name='it_success'),
    path('application/', application_view, name='application'),
    path('order_success/', product_success_view, name='order_success'),
]

wholphin/urls.py
from django.urls import path
from .views import Home, about, HomePage, CourseHome, services, register_form_vew, CourseDetail, Course_Apply, feedback_view, register_view, contact,terms, register_success

app_name = 'wholphin'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('h/', HomePage.as_view(), name='homepage'),
    path('about/', about, name='about'),
    path('services/', services, name='services'),
    path('courses/', CourseHome.as_view(), name='course'),
    path('<int:pk>/', CourseDetail.as_view(), name='courseprice'),
    path('<int:courses_id>/<int:pk>/', Course_Apply.as_view(), name='apply'),
    path('feedback/', feedback_view, name='feedback'),
    path('contact/', contact, name='contact'),
    path('register/', register_view, name='register'),
    path('t&c/', terms, name='t&c'),
    #path('lay', lay, name='lay'),
    path('register_success/', register_success, name='register_success'),
    path('registered/', register_form_vew, name='registered'),
]

wholphinplus/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from .views import layout, indexs,it, con


urlpatterns = [
    path('ad/', admin.site.urls),
    path('', include('wholphin.urls')),
    path('products/', include('products.urls')),
    path('in/', indexs, name='in'),
    path('it/', it, name='it'),
    path('con/', con, name='con'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Wholphinplus Venture'
admin.site.index_title = 'welcome to who'
admin.site.site_title='wholphin'

wholphin/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Courses(models.Model):
    course_title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='picture')
    image1 = models.ImageField(upload_to='picture')
    description = models.TextField()
    duration = models.PositiveIntegerField()
    amount = models.PositiveIntegerField()
    date_pub = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.duration} months of {self.course_title} for N{self.amount}'

    def get_absolute_url(self):
        return reverse('wholphin:courseprice', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = 'Courses'


class CoursesDetail(models.Model):
    course_subtitle = models.CharField(max_length=100)
    description = models.TextField()
    image1 = models.ImageField(upload_to='picture')
    courses = models.ForeignKey(Courses, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Courses' Detail"

    def __str__(self):
        return self.course_subtitle


GENDER = (('MALE', 'Male'), ('FEMALE', 'Female'))
COURSE = (('Choose...', 'Choose...'), ('AI', 'Artificial Intelligence'), ('WB', 'Web Development'),
          ('ML', 'Machine Learning'), ('DL', 'Deep Learning'), ('RB', 'Robotics'), ('APP', 'App Development'),
          ('CP', 'Computer Programming'), ('GD', 'Graphic Design'), ('WP', 'Word Processing'))
STATE = (('Choose...', 'Choose...'),('ab', 'Abia'), ('ada', 'Adamawa'), ('aks', 'Akwa Ibom'), ('bau', 'Bauchi'), ('bay', 'Bayelsa'), ('ben', 'Benue'), ('bor', 'Borno'),
         ('crs', 'Cross River'), ('del', 'Delta'), ('ebo', 'Ebonyi'), ('Ed', 'Edo'), ('Eki', 'Ekiti'), ('Enu', 'Enugu'), ('Gom', 'Gombe'),
         ('Im','Imo'), ('Jiga', 'Jigawa'), ('Kadu', 'Kaduna'), ('Kan', 'Kano'), ('Kat', 'Katsina'), ('Keb', 'Kebbi'), ('Kog', 'Kogi'),
         ('Kwa', 'Kwara'), ('Lag', 'Lagos'), ('Nasa', 'Nasarawa'), ('Nig', 'Niger'), ('Ogu', 'Ogun'), ('Ond', 'Ondo'), ('Osu', 'Osun'),
         ('Oy', 'Oyo'), ('Pla', 'Plateau'), ('Rs', 'Rivers'), ('Sok', 'Sokoto'), ('Tara', 'Taraba'), ('Yob', 'Yobe'),
         ('Zamfa', 'Zamfara'), ('FCT', 'Abuja'))


class UsersComment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    suggestion = models.TextField()

    def __str__(self):
        return self.name


class StudentRegistered(models.Model):
    surname = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    other_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone_number = models.PositiveIntegerField()
    home_address = models.CharField(max_length=100)
    contact_address = models.CharField(max_length=100)
    LGA_of_origin = models.CharField(max_length=100)
    state_of_origin = models.CharField(max_length=100, choices=STATE)
    Gender = models.CharField(max_length=7, choices=GENDER)
    course = models.CharField(max_length=100, choices=COURSE)
    t_and_c = models.BooleanField(default=False)
    date_registered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.surname} {self.first_name} has registered online for {self.course} on {self.date_registered}'

    class Meta:
        verbose_name_plural = "Student Registered"


class Students(models.Model):
    id = models.AutoField(primary_key=True)
   # admin = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    gender = models.CharField(max_length=50)
    profile_pic = models.FileField()
    address = models.TextField()
    course_id = models.ForeignKey(Courses, on_delete=models.DO_NOTHING, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return self.address


class Carousel(models.Model):
    image = models.ImageField(upload_to='carousel')
    title = models.CharField(max_length=30)
    desc = models.CharField(max_length=100)

    def __str__(self):
        return self.title

wholphin/forms.py
from django import forms
from .models import UsersComment, StudentRegistered, Courses


class UsersCommentForm(forms.ModelForm):
    email = forms.EmailField(label="Email", max_length=50, widget=forms.EmailInput(attrs={"class": "form-control", 'placeholder':'comment@gmail.com'}))
    name = forms.CharField(label="Name", max_length=50, widget=forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Name, start with surname'}))
    suggestion = forms.CharField(label='Comment', max_length=2000, widget=forms.Textarea(attrs={'class': "form-control", 'placeholder':'Drop your comment here'}))

    class Meta:
        model = UsersComment
        fields = '__all__'


GENDER = (('Choose...', 'Choose....'), ('MALE', 'Male'), ('FEMALE', 'Female'))
COURSE = (('Choose...', 'Choose...'), ('AI', 'Artificial Intelligence'), ('WB', 'Web Development'),
          ('ML', 'Machine Learning'), ('DL', 'Deep Learning'), ('RB', 'Robotics'), ('APP', 'App Development'),
          ('CP', 'Computer Programming'), ('GD', 'Graphic Design'), ('WP', 'Word Processing'))
STATE = (('Choose...', 'Choose...'),('ab', 'Abia'), ('ada', 'Adamawa'), ('aks', 'Akwa Ibom'), ('bau', 'Bauchi'), ('bay', 'Bayelsa'), ('ben', 'Benue'), ('bor', 'Borno'),
         ('crs', 'Cross River'), ('del', 'Delta'), ('ebo', 'Ebonyi'), ('Ed', 'Edo'), ('Eki', 'Ekiti'), ('Enu', 'Enugu'), ('Gom', 'Gombe'),
         ('Im','Imo'), ('Jiga', 'Jigawa'), ('Kadu', 'Kaduna'), ('Kan', 'Kano'), ('Kat', 'Katsina'), ('Keb', 'Kebbi'), ('Kog', 'Kogi'),
         ('Kwa', 'Kwara'), ('Lag', 'Lagos'), ('Nasa', 'Nasarawa'), ('Nig', 'Niger'), ('Ogu', 'Ogun'), ('Ond', 'Ondo'), ('Osu', 'Osun'),
         ('Oy', 'Oyo'), ('Pla', 'Plateau'), ('Rs', 'Rivers'), ('Sok', 'Sokoto'), ('Tara', 'Taraba'), ('Yob', 'Yobe'),
         ('Zamfa', 'Zamfara'), ('FCT', 'Abuja'))


class RegisterForm(forms.ModelForm):
    email = forms.EmailField(label="Email", max_length=50, widget=forms.EmailInput(
        attrs={"class": "form-control", 'placeholder': 'register@email.com'}))

    surname = forms.CharField(label="Surname", max_length=50, widget=forms.TextInput(attrs={"class": "form-control",
                                                                                                'placeholder': 'Surname'}))
    first_name = forms.CharField(label="First Name", max_length=50, widget=forms.TextInput(
            attrs={"class": "form-control", 'placeholder': 'First Name'}))
    other_name = forms.CharField(label="Other Name", max_length=50, widget=forms.TextInput(
            attrs={"class": "form-control", 'placeholder': 'Other Names'}))
    phone_number = forms.CharField(label="Phone Number", max_length=50, widget=forms.NumberInput(
            attrs={"class": "form-control", 'placeholder': '+2349011914759'}))
    date_of_birth = forms.DateField(label="Date of Birth", widget=forms.DateInput(
            attrs={"class": "form-control", 'placeholder': 'YYY-MM-DD'}))
    home_address = forms.CharField(label="Home Address", max_length=100, widget=forms.TextInput(
            attrs={"class": "form-control", 'placeholder': 'Home Address'}))
    contact_address = forms.CharField(label="Contact Address", max_length=100, widget=forms.TextInput(
        attrs={"class": "form-control", 'placeholder': 'Contact Address'}))
    LGA_of_origin = forms.CharField(label="LGA of Origin", max_length=50, widget=forms.TextInput(
            attrs={"class": "form-control", 'placeholder': 'LGA of Origin'}))
    state_of_origin = forms.ChoiceField(label="State of Origin", choices=STATE, widget=forms.Select(
            attrs={"class": "form-control", 'placeholder': 'State of Origin'}))
    Gender = forms.ChoiceField(choices=GENDER, widget=forms.Select(attrs={"class": "form-control",
                                                                          'placeholder': 'Choose gender'}))
    course = forms.ChoiceField(label="Course", choices=COURSE, widget=forms.Select(attrs={"class": "form-control"}))
    t_and_c = forms.BooleanField(label="Terms and Conditions",required=True)

    class Meta:
        model = StudentRegistered
        fields = '__all__'

wholphin/views.py
from email import message
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView

from products.models import Products
from .models import Courses, CoursesDetail, UsersComment, StudentRegistered, Carousel
from .forms import UsersCommentForm, RegisterForm
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage


class Home(ListView):
    model = Courses
    context = Products
    comment = UsersCommentForm
    template_name = 'wholphin/home.html'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['course1'] = Courses.objects.all()[:4]
        context['service'] = Products.objects.all()[:4]
        context['comment'] = UsersComment.objects.all()
        context['car'] = Carousel.objects.all()
        return context


class HomePage(ListView):
    model = Courses
    context = Products
    comment = UsersCommentForm
    template_name = 'wholphin/homepage.html'


    def get_context_data(self, **kwargs):
        context = super(HomePage, self).get_context_data(**kwargs)
        context['course1'] = Courses.objects.all()[:4]
        context['service'] = Products.objects.all()[:4]
        context['comment'] = UsersComment.objects.all()
        return context



#@login_required(login_url='wholphin:home')
def about(request):
    return render(request, 'wholphin/about.html')


def contact(request):
    return render(request, 'wholphin/contact.html')


def terms(request):
    return render(request, 'wholphin/terms.html')


# def register_view(request):
#     form = RegisterForm
#     if request.method == 'POST':
#         form = RegisterForm(request.POST)
#         if form.is_valid():
#             form.save()
#             h = 'We appreciate your effort to comment, its important to us'
#             messages.add_message(request, messages.SUCCESS, h)
#             return HttpResponseRedirect(reverse('wholphin:home'))
#     return render(request, 'wholphin/register.html', {'form': form})


class CourseHome(ListView):
    model = Courses
    #queryset = Courses.objects.all()[:4]
    #context_object_name = 'courses'
    template_name = 'wholphin/courses.html'

    def get_context_data(self, **kwargs):
        context = super(CourseHome, self).get_context_data(**kwargs)
        context['course1'] = Courses.objects.all()[:4]
        context['course2'] = Courses.objects.all()[4:7]
        #context['course3'] = Courses.objects.all()[7:9]
        context['course4'] = Courses.objects.all()[7:9]
        context['course5'] = Courses.objects.all()[14:18]
        context['course6'] = Courses.objects.all()[18:22]
        return context


class CourseDetail(DetailView):
    model = Courses
    context_object_name = 'price'
    template_name = 'wholphin/coursesprice.html'


class Course_Apply(DetailView):
    model = CoursesDetail
    template_name = 'wholphin/courseapply.html'
    context_object_name = 'apply'


def services(request):
    return render(request, 'wholphin/services.html')

#
# def lay(request):
#     return render(request, 'layout.html')


def feedback_view(request):
    form = UsersCommentForm
    if request.method == 'POST':
        form = UsersCommentForm(request.POST)
        if form.is_valid():
            form.save()
            h = 'We appreciate your effort to comment, its important to us'
            messages.add_message(request, messages.SUCCESS, h)
            return HttpResponseRedirect(reverse('wholphin:home'))
    return render(request, 'wholphin/feedback.html', {'form': form})


def register_view(request):
    form = RegisterForm
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            # h = 'You have successfully registered for a course'
            # messages.add_message(request, messages.SUCCESS, h)
            return HttpResponseRedirect(reverse('wholphin:register_success'))
    return render(request, 'wholphin/register.html', {'form': form})


def register_success(request):

    return render(request, 'wholphin/register_success.html')


def register_form_vew(request):
    context = StudentRegistered.objects.all()[:3]
    return render(request, 'wholphin/printform.html', {'context': context})

wholphin/templates/wholphin/contact.html
{% extends 'header.html' %}

{% load static %}

{% block content %}
<header class="jumbotron" style="display:flex;justify-content:space-around;height:450px">
        <div style="margin-top:90px;" class="container-fluid"><h3>Wholphinplus Team <br>Contact Us any time </h3><p>
            </p><a href="Tel: +2349048178433" class="alert alert-primary"
                                                     style="">Call for action!</a></div>

        <div class="" style="background-image:url({% static 'image/images - 2021-04-05T135044.058.jpeg' %});
        background-repeat:no-repeat;width:100rem; height:100%">

      </div>
    </header>




<div class="container">
    <div class="row mb-5">
          <div class="col-md-6 col-lg-6">
            <div class="ftco-footer-widget mb-5">
            	<div class="block-23 mb-3">
<img class="col-md-12 col-lg-12" width="500" height="500" src="{% static 'image/images - 2021-04-06T154933.981.jpeg' %}">
	            </div>
            </div>
          </div>


              <div class="col-md-6 col-lg-6">
            <div class="ftco-footer-widget mb-5">
            	<div class="block-23 mb-3">
 <h6 style="padding-left:30px;padding-top:150px;font-size:20px;font-family:san serif">Do you need assistance with our services,
   course enrolment, job opening and more enquiries about Wholphinplus?<p></p>
        <p>Our AI Assistance will get the help that you need. </p></h6>
                            <center><a href="" class="btn btn-success" style="color:white"> Get started</a></center>

	            </div>
            </div>
          </div>
        </div>
</div>

{% endblock %}

wholphin/templates/wholphin/courseapply.html
<!--{% load static %}-->

<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Apply form</title>-->
<!--    <link rel="stylesheet" href="{% static 'path/to/font-awesome/css/font-awesome.min.css' %}">-->
<!--    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}">-->
<!--</head>-->
<!--<body>-->

<!--{% block content %}-->
<!--<div class="container" style="sans-serif;">-->
<!--    <div class="jumbotron">-->
<!--   <center> <div>-->
<!--       <h1>WHOLPHINPLUS VENTURE</h1>-->
<!--    <h4>THE FUTURE IS NOW</h4>-->
<!--   <h5>Phone: +2349046933458, +2349048178433</h5>-->
<!--    <h5>Email: wholphinplus@gmail.com</h5>-->
<!--    <h5>Website: wholphinplus.com</h5>-->
<!--    </div>-->
<!--       <br>-->
<!--    <div><h4 style="color:white;background-color:black;width:30%">ADMISSIONION FORM</h4></div>-->
<!--       <p><i><b>Please write your name in full and in capital letters starting with surname</b></i></p>-->
<!--        </center>-->
<!--    <div>-->

<!--          <div style="color:white;background-color:black;width:100%">1. <center><h5 style="margin-top:-25px">PERSONAL DATA</h5></center></div>-->



<!--        <div style="color:white;background-color:black;width:100%">1. <center><h5 style="margin-top:-25px">PAYMENT METHOD</h5></center></div>-->
<!--<input type="radio" name="gender"> Full Payment <br>-->
<!--        <input type="radio" name="gender"> By Installment -&#45;&#45;-->
<!--                      (first instalment: 70%  second instalment: The remaining 30% be paid after the at the beginning of the second month of the training)</input>-->



<!--         <div style="color:white;background-color:black;width:100%">2. <center><h5 style="margin-top:-25px">FOR UNDERGRADUATE ONLY</h5></center></div>-->





<!--         <div style="color:white;background-color:black;width:100%">3. <center><h5 style="margin-top:-25px">COURSES OFFERED</h5></center></div>-->
<!--{{apply.course_title|upper|linebreaks}}-->
<!--{{apply.amount}}<br>-->
<!--{{apply.duration}} months-->
<!--         <div style="color:white;background-color:black;width:100%">4. <center><h5 style="margin-top:-25px">COURSES DURATION</h5></center></div>-->
<!--    </div>-->
<!--</div>-->
<!--    </div>-->
<!--{% endblock %}-->
<!--</body>-->
<!--</html>-->

wholphin/templates/wholphin/courses.html
{% extends 'header.html' %}
{% load static %}
<body>
{% block content %}

     <div class="card-text-center">
         <img class="card-img-top" src="{% static 'image/images - 2021-04-08T121758.483.jpeg' %}" height="500px" width="100%">
          <center><h3 style="margin-top:-330px; color:white" class="container-fluid"><strong>Courses</strong>
              <br>Enroll for professional courses.<br>
            <a href="{% url 'wholphin:register' %}"
               target="_blank" class="btn btn-primary" >Apply Now!</a></h3>
              </center>
    </div>
<div style="font-family:san-serif;margin-top:30px" class="container-fluid px-4">


      <!--- SECTION ONE COURSES--->

     <div class="row text-left" style="background-color:white;margin-top:250px; display:flex;justify-content:space-around" id="pro">

   {% for course in course1 %}
    <div class="col-lg-3 col-md-6 mb-6">
      <div  class="card text-left"   style="border:01px solid white; display:flex;justify-content:space-around">
    <img class="card-img-top" src=" {{course.image.url}}" height="300rem" width="50px">
          <div class="card-footer">
          <div style="background-color:"><h4 style="color:#add"><a href="{{course.get_absolute_url}}" style="padding-left:01px">
        {{course.course_title.capitalize}}</a></h4></div>
          <div class="card-text" style="font-size:20px;justify-content:space-around; display:lex-around;padding:10px ">
              {% if course.description|wordcount <= 15 %}
           {{course.description}}
          {% else %}
    {{course.description|truncatewords:26}}
              <div>
              <a href="{{course.get_absolute_url}}" style="width:120px;border:none;"> Apply Now</a>
                  </div>
          {% endif %}
          </div>
          </div>
          <br>
      </div>

    </div>
    {% endfor %}

    </div>


    <!--- SECTION TWO COURSES--->
 <div class="row text-left" style="background-color:white;margin-top:20px; display:flex;justify-content:space-around" id="pro">
  {% for course in course2 %}
    <div class="col-lg-3 col-md-6 mb-4">
      <div  class="card text-left"   style="border:01px solid white; display:flex;justify-content:space-around">
    <img class="card-img-top" src=" {{course.image.url}}" height="300rem" width="50px">
          <div class="card-footer">
          <div style="background-color:"><h5 style="color:#add"><a href="{{course.get_absolute_url}}" style="font-family:san serif; padding-left:-5px">
        {{course.course_title.capitalize}}</a></h5></div>
          <div class="card-text" style="font-size:20px;justify-content:space-around; display:lex-around;padding:10px ">
              {% if course.description|wordcount <= 15 %}
           {{course.description}}
          {% else %}
    {{course.description|truncatewords:40}}
              <div>
              <a href="{{course.get_absolute_url}}" style="width:120px;border:none;"> Apply Now</a>
                  </div>
          {% endif %}
          </div>
          </div>
      </div>

    </div>
    {% endfor %}

    </div>


</div>


    <!--- SECTION THREE COURSES--->






<!section four courses--->

     <header class="jumbotron" style="display:flex;justify-content:space-around;height:450px">
        <h4 class="container-fluid" style="margin-top:8%">MISCELLENEOUS COURSES<br>Latest update on miscelleneous courses.<br><br>
            <a href="Tel: +2349048178433" class="btn btn-primary">Call for action!</a></h4>

        <div class="img-responsive"  style="background-image:url({% static 'image/images.jpeg' %});
        background-repeat:no-repeat;width:100%; height:auto">

      </div>
    </header>

<div class="container-fluid px-6">
      <div class="row text-left" style="background-color:white;margin-top:20px; display:flex;justify-content:space-around">
 {% for course in course4 %}
    <div class="col-lg-3 col-md-6 mb-4">
      <div  class="card text-left"   style="width:450px;border:01px solid white; display:flex;justify-content:space-around">
    <img class="card-img-top" src=" {{course.image.url}}" height="300rem" width="50px">
          <div class="card-footer">
          <div style="background-color:"><h5 style="font-size:30px;color:#add"><a href="{{course.get_absolute_url}}" style="font-family:san serif; padding-left:px">
        {{course.course_title.capitalize}}</a></h5></div>
          <div class="card-text" style="font-size:20px;justify-content:space-around; display:lex-around;padding:px ">
              {% if course.description|wordcount <= 15 %}
           {{course.description}}
          {% else %}
    {{course.description|truncatewords:40}}
              <div>
              <a href="{{course.get_absolute_url}}" style="width:120px;border:none;"> Apply Now</a>
                  </div>
          {% endif %}
          </div>
          </div>
      </div>

    </div>
    {% endfor %}

    </div>















<!--- SECTION FOUR COURSES

    ----SECTION Five COURSES-----

   <div class="row text-left" style=" background-color:white; display:flex;justify-content:space-around">

    {% for course in course5 %}
    <div class="col-lg-3 col-md-6 mb-4" >
      <div  class="card text-center"   style="border:1px solid white; display:flex;justify-content:space-around">
        <div style="background-color:"><h6 style="color:#add"><a href="{{course.get_absolute_url}}" style="padding-left:20px">
        {{course.course_title.capitalize}}</a></h6></div>
    <img class="card-img-top" src=" {{course.image.url}}" height="130rem" width="100px">
          <div class="card-text" style="justify-content:space-around; display:lex-around;padding:10px ">
              {% if course.description|wordcount <= 15 %}
           {{course.description}}
          {% else %}
    {{course.description|truncatewords:10}}
              <button class="btn btn-success"><a href="{{course.get_absolute_url}}" style="color:white"> Apply Now</a></button>
          {% endif %}
          </div>

      </div>

    </div>
    {% endfor %}

    </div>

--->


</div>
{% endblock %}
</body>

wholphin/templates/wholphin/coursesprice.html
{% extends 'header.html' %}
{% load static %}
<head>
    <title>Courses' Detail</title>
    <link rel="stylesheet" href="{% static 'path/to/font-awesome/css/font-awesome.min.css' %}">
</head>

{% block content %}


    <header class="jumbotron my-4" style="display:flex;justify-content:space-around;height:450px">
    <h4 class="container-fluid" style="margin-top:50px"><b >{{price.course_title|upper|linebreaks}}</b>
        <p style="font-family:Brush Script MT">{{price.description|truncatewords:10}}</p>
        <br><a href="{% url 'wholphin:register' %}" class="btn btn-primary">Apply Now!</a></h4>

        <div class="card-text-center" >

             <img class="card-img-top" src=" {{price.image1.url}}" height="100%" width="100rem">

      </div>
         </header>
<div style="font-family:sans-serif;margin-top:30px" class="container py-6">
  <div class="row text-left" id="top">

      <div class="jumbotron" style="border:none;background:none;font-size:20px;font-family:san serif;">{{price.description}}</div>
    </div>

     <div class="row text-left" style="margin-top:px; background-color:white; display:flex;justify-content:space-around" id="pro">

    {% for price in price.coursesdetail_set.all %}
    <div class="col-lg-4 col-md-6 mb-4" >
      <div  class="card text-left"   style="width:100%;border:01px solid white; display:flex;justify-content:space-around">
   <img class="card-img-top" src=" {{price.image1.url}}" height="250px" width="50%">
          <div class="card-footer">
          <div id="wholphinplus" style="background-color:"><h6 style="color:#add"><a href="#wholphinplus" style="padding-left:1px;font-size:20px" class="">
        {{price.course_subtitle}}</a></h6></div>
          <div class="card-text" style="justify-content:space-around; display:lex-around;padding:1px " >
             {% if price.description|wordcount <= 15 %}
           {{price.description}}
          {% else %}
    {{price.description|truncatewords:36}}

          {% endif %}
          </div>
          </div>
      </div>

    </div>
    {% endfor %}

    </div>





         <div class="">
<div class="card-footer">
   <h4>Duration: {{price.duration}} months<br>
       Amount: <strike>N</strike>{{price.amount}}</h4>
    </div>
</div>
    <a href="{% url 'wholphin:register' %}"><button class="alert alert-primary">Apply Now</button></a>
</div>

{% endblock %}

wholphin/templates/wholphin/printform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
{% for context in context %}
<div class="card">
{{context}}
    <img src="{{context.passport.url}}">
    </div>
{% endfor %}

    </div>
</body>
</html>

wholphin/templates/wholphin/register_success.html
{% extends 'printingheader.html' %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container">
    <div class="jumbotron" style="margin:20%">
        <center> <div >
          <div >
      <h3 >Your application has been submitted successfully</h3>
        <h5>We will get back to you as soon as possible</h5>
    </div>
             <a href="/">Back to home</a> || <a href="{% url 'wholphin:course' %}">View our Courses</a>
            </div>
        </center>
        </div>
</div>
{% endblock %}
</body>
</html>