products/urls.py
from django.urls import path
from .views import ProductDetailView, ProductView, order, get_started, eportal, it_view, it_success, application_view, it_manual_view, product_success_view

app_name = 'wholphinplus'

urlpatterns = [
    path('', ProductView.as_view(), name='products'),
    path('<int:pk>/', ProductDetailView.as_view(), name='productdetail'),
    path('order/', order, name='order'),
    path('get{}started/', get_started, name='get started'),
    path('eportal/', eportal, name='eportal'),
    path('it1/', it_view, name='it1'),
    path('it1l/', it_manual_view, name='it1l'),
    path('it_success/', it_success, name='it_success'),
    path('application/', application_view, name='application'),
    path('order_success/', product_success_view, name='order_success'),
]

wholphin/urls.py
from django.urls import path
from .views import Home, about, HomePage, CourseHome, services, register_form_vew, CourseDetail, Course_Apply, feedback_view, register_view, contact,terms, register_success

app_name = 'wholphin'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('h/', HomePage.as_view(), name='homepage'),
    path('about/', about, name='about'),
    path('services/', services, name='services'),
    path('courses/', CourseHome.as_view(), name='course'),
    path('<int:pk>/', CourseDetail.as_view(), name='courseprice'),
    path('<int:courses_id>/<int:pk>/', Course_Apply.as_view(), name='apply'),
    path('feedback/', feedback_view, name='feedback'),
    path('contact/', contact, name='contact'),
    path('register/', register_view, name='register'),
    path('t&c/', terms, name='t&c'),
    #path('lay', lay, name='lay'),
    path('register_success/', register_success, name='register_success'),
    path('registered/', register_form_vew, name='registered'),
]

wholphinplus/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from .views import layout, indexs,it, con


urlpatterns = [
    path('ad/', admin.site.urls),
    path('', include('wholphin.urls')),
    path('products/', include('products.urls')),
    path('in/', indexs, name='in'),
    path('it/', it, name='it'),
    path('con/', con, name='con'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Wholphinplus Venture'
admin.site.index_title = 'welcome to who'
admin.site.site_title='wholphin'

templates/app.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block title %}{% endblock %}
    <title>Example Template</title>

    {% load static %}
    <!-- Custom fonts for this template-->
    <link href="{% static 'static/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'static/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'static/css/sb-admin.css' %}" rel="stylesheet">
    {% block stylesheet %}{% endblock %}
</head>

<body id="page-top">

<!-- headers-->
{% include "elements/header.html" %}

<div id="wrapper">

    <!-- Sidebar -->
    {% include "elements/sidebar.html" %}

    <!-- /.content-wrapper -->
    {% block body %}{% endblock %}
</div>
<!-- /#wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- feedback Modal-->
<div class="modal fade" id="feedbackModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "feedback" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
               <a class="btn btn-primary" href="{% url 'wholphin:feedback' %}">feedback</a>
            </div>
        </div>
    </div>
</div>


<!-- Bootstrap core JavaScript-->
<script src="{% static 'static/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'static/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'static/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static 'static/vendor/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'static/vendor/datatables/dataTables.bootstrap4.js' %}"></script>

<!-- Demo scripts for this page-->
<script src="{% static 'static/js/demo/datatables-demo.js' %}"></script>
<!-- Custom scripts for all pages-->
<script src="{% static 'static/js/sb-admin.min.js' %}"></script>
<script>
    $(".alert-success").fadeTo(2000, 500).slideUp(500, function(){
        $(".alert-success").slideUp(500);
    });
    $(".alert-error").fadeTo(2000, 500).slideUp(500, function(){
        $(".alert-error").slideUp(500);
    });
</script>

{% block javascript %}{% endblock %}
</body>

</html>

templates/footer.html
 {% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Wholphinplus</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<!-- Footer -->
<div class="container" style="margin-top:10px;margin-left:-5px">


 </div>

      <div class="container">

  <div class="form-row">
     <h5 style="font-family:Liberation Mono">Follow Wholphinplus</h5>
  <div class="form-group" style="margin-left:10px">

    <a href="https://web.facebook.com/Wholphinplus/" target="_blank" ><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
 </svg></a>
    </div>

    <div class="form-group" style="margin-left:10px">
    <a href="https://twitter.com/wholphinplus?s=08" target="_blank" > <svg xmlns="http://www.w3.org/2000/svg"  width="30" height="30" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
 </svg></a>
    </div>

     <div class="form-group" style="margin-left:10px">
    <a href="https://wa.me/message/JHSJVFKZOZEMD1" target="_blank" ><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
  <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
  </svg></a>

    </div>

  </div>
      </div>
    <footer class="card bg-dark">
<div class="card-body">
        <div class="row mb-5">
          <div class="col-md-6 col-lg-4">
            <div class="ftco-footer-widget mb-5">
            	<div class="block-23 mb-3">
 <img class="" style="margin-top:15px;margin-left:8px"  src="{% static 'image/logo_plus.png' %}" height="60px" width="60px">
 <a href="/" style="color:white;"  > Wholphinplus <h6 style="font-size:25px;margin-top:-35px;margin-left:75px"> Venture</h6></a>
	            </div>
            </div>
          </div>


          <div class="col-md-6 col-lg-4">
            <div class="ftco-footer-widget mb-5">
                <h2 class="ftco-heading-2" ><strong><h5 style="margin-top:20px;color:white">Students</h5></strong></h2>
            	<div class="block-23 mb-3">
	              <ul>
	                 <li> <a href="{% url 'wholphin:about' %}" style="color:white">Accessibility</a></li>
	                <li><a href="" style="color:white">Payment Method</a></li>
	                <li><a href="{% url 'wholphin:course' %}" style="color:white">Courses</a></li>
	              </ul>
	            </div>
            </div>
          </div>

    <div class="col-md-6 col-lg-4">
            <div class="ftco-footer-widget mb-5">
                <h2 class="ftco-heading-2" ><strong><h5 style="margin-top:20px;color:white">Company</h5></strong></h2>
            	<div class="block-23 mb-3">
	              <ul>
	                 <li><a href="{% url 'wholphin:about' %}" style="color:white">About Us</a></li>
	                <li><a href="" style="color:white">Privacy policy</a></li>
                      <li><a href="{% url 'wholphin:services' %}" style="color:white">Services</a></li>
	              </ul>
	            </div>
            </div>
          </div>

        <div class="col-md-6 col-lg-4">
            <div class="ftco-footer-widget mb-5">
                <h2 class="ftco-heading-2" ><strong><h5 style="color:white">Wholphinplus Venture</h5></strong></h2>
            	<div class="block-23 mb-3">
	              <ul>
	                 <li><a href="{% url 'wholphinplus:products' %}" style="color:white">Products</a></li>
	                <li><a href="{% url 'wholphinplus:application' %}" style="color:white">Vacancy</a></li>
	                <li><a href="{% url 'wholphin:contact' %}" style="color:white">Customer care</a></li>
	              </ul>
	            </div>
            </div>
          </div>

            <div class="col-md-6 col-lg-4">
            <div class="ftco-footer-widget mb-5">
                <h2 class="ftco-heading-2" ><strong><h5 style="color:white">Programming Language</h5></strong></h2>
            	<div class="block-23 mb-3">
	              <ul>
	                 <li><a target="_blank" href="https://en.wikipedia.org/wiki/Python_(programming_language)" style="color:white">Python</a></li>
	                <li><a target="_blank" href="https://en.wikipedia.org/wiki/PHP" style="color:white">PHP</a></li>
	                <li><a target="_blank" href="https://en.wikipedia.org/wiki/HTML" style="color:white">HTML</a></a></li>
                       <li><a target="_blank" href="https://en.wikipedia.org/wiki/CSS" style="color:white">CSS</a></li>
	                <li><a target="_blank" href="https://en.wikipedia.org/wiki/JavaScript" style="color:white">Javascript</a></li>
	                <li> <a target="_blank" href="https://en.wikipedia.org/wiki/Microsoft_Visual_Studio" style="color:white">Visual Studio</a></li>
	              </ul>
	            </div>
            </div>
          </div>

            <div class="col-md-6 col-lg-4">
            <div class="ftco-footer-widget mb-5">
                <h2 class="ftco-heading-2" ><strong><h5 style="color:white">Contact Info</h5></strong></h2>
            	<div class="block-23 mb-3">
	              <ul>
	                 <li><span class="icon icon-map-marker" style="color:white"></span><p></p><span class="text" style="color:white">No. 9 Ama-Aka Street, Use Offot, Uyo, Akwa Ibom State, Nigeria.</span></li><br>
	                <li><a style="color:white" href="#"><span class="icon icon-phone"></span><span class="text">+2349046933458, +2349048178433</span></a></li>
	                <li><a style="color:white" href="#"><span class="icon icon-envelope"></span><span class="text">Wholphinplus@gmail.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>

            <div class="col-md-12 col-lg-12">
            <div class="ftco-footer-widget mb-5">
               <center> <h2 class="ftco-heading-2" style="color:white"><strong><a href="{% url 'wholphin:feedback' %}" style="color:white"><button class="btn btn-success">Feedback</button></a></strong></h2>
               </center><div class="block-23 mb-3">

	                <center><progress translate="yes" style="width:90px">feed</progress></center>

	            </div>
            </div>
          </div>

            <div class="col-md-12 col-lg-12">
            <div class="">
     <center>
<h6 style="font-family:Roboto" class="m-0 text-center text-white">Copyright &copy; Wholphinplus Venture {% now "Y" %}</h6>
</center>
            </div>
          </div>


        </div>
</div>





    </footer>

 <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/header.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Wholphinplus Venture</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	  	<link rel="icon" type="image/png" href="{% static 'logo/images/icons/logo_plus.png' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">


    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'home/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'home/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'home/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'home/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'home/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  </head>
<body>

 <nav class="navbar navbar-expand-lg navbar-light ftco_navbar bg-dark ftco-navbar-dark" id="ftco-navbar">
	    <div class="container" >

             <a class="navbar-small" href="/"><img  src="{% static 'image/logodesign2.png' %}" height="30px" width="200px"></a>

	      <button style="color:#fff;" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                  aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	     <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto" style="font-size:20px;">
	          <li class="nav-item active"> <a class="nav-link active" style="font-size:15px;color:white" aria-current="page" href="/">Home</a></li>

                 <li class="nav-item active">
                 <a class="nav-link active" style="font-size:15px;color:white" aria-current="page" href="{% url 'wholphin:course' %}">Courses</a></li>

                <li class="nav-item active"> <a class="nav-link active" style="font-size:15px;color:white" aria-current="page" href="{% url 'wholphin:services' %}">Services</a></li>

                 <li class="nav-item active"> <a class="nav-link active" style="font-size:15px;color:white" href="{% url 'wholphin:contact' %}">Contact</a></li>

                 <li class="nav-item active"><a class="nav-link active" style="font-size:15px;color:white" href="{% url 'wholphin:about' %}">About Us</a></li>

	          <li class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle"  href="{% static 'static/#" id="dropdown04" data-toggle="dropdown" style="font-size:15px;color:white" aria-haspopup="true" aria-expanded="false">More</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
                  <a class="dropdown-item" href="{% url 'wholphinplus:products' %}">Products</a>
<a class="dropdown-item" href="{% url 'wholphinplus:application' %}">Career</a>
                  <a class="dropdown-item" href="{% url 'wholphin:register' %}"
               target="_blank" >Apply Now!</a>
                <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'wholphin:t&c' %}">Our Terms</a>
                  <a class="dropdown-item" href="">Gallery</a>
              </div>
            </li>
	        </ul>
	      </div>
	    </div>
	  </nav>




















<!END OF NAVBAR-->
{% block content %}{% endblock %}
{% include 'footer.html' %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

 <script src="{% static 'home/js/jquery.min.js' %}"></script>
  <script src="{% static 'home/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'home/js/popper.min.js' %}"></script>
  <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'home/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'home/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'home/js/aos.js' %}"></script>
  <script src="{% static 'home/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'home/js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'home/js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'home/js/google-map.js' %}"></script>
  <script src="{% static 'home/js/main.js' %}"></script>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
welcome
<a href="{% url 'login' %}">login</a>
<a href="{% url 'wholphin:course' %}">site</a>
</body>
</html>

templates/it.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="/it" target="_blank" download="itform.pdf">download</a>
<embed src="{% static '_it/itform.pdf' %}" style="width:1500px;height:1000px">
</body>
</html>

templates/modal.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Modal Popup in HTML and CSS</title>
	<link rel="stylesheet" type="text/css" href="{% static 'modal_static/styles.css' %}">
</head>
<body>
<div class="wrapper" >
	<button class="cancel_btn" style="height:20px;background:none;color:green">Printing</button>

	<div class="modal_popup" style="width:20%;margin-left:-40px">
		<div class="bg_shadow"></div>
		<div class="popup" style="width:100wv;margin-left-200px">
			<div class="popup_head">
				About Printing Services?

				<button class="close_btn"></button>
			</div>
			<div class="popup_body">

				DESCRIPTION ABOUT THE SERVICE

			</div>
			<div class="popup_foot">
				<button class="popup_btn popup_cancel_btn">Cancel</button>
				<button class="popup_btn popup_confirm_btn">Confirm</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	var cancel_btn = document.querySelector(".cancel_btn");
	var modal_popup = document.querySelector(".modal_popup");

	var close_btn = document.querySelector(".close_btn");
	var popup_cancel_btn = document.querySelector(".popup_cancel_btn");
	

	cancel_btn.addEventListener("click", function(){
		modal_popup.classList.add("active");
	})

	close_btn.addEventListener("click", function(){
		modal_popup.classList.remove("active");
	})
	popup_cancel_btn.addEventListener("click", function(){
		modal_popup.classList.remove("active");
	})
</script>

</body>
</html>

templates/printingheader.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Wholphinplus Venture</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	  	<link rel="icon" type="image/png" href="{% static 'logo/images/icons/logo_plus.png' %}"/>


    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'home/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'home/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'home/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'home/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'home/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  </head>
<body>

<!END OF NAVBAR-->
{% block content %}{% endblock %}
 <script src="{% static 'home/js/jquery.min.js' %}"></script>
  <script src="{% static 'home/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'home/js/popper.min.js' %}"></script>
  <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'home/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'home/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'home/js/aos.js' %}"></script>
  <script src="{% static 'home/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'home/js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'home/js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'home/js/google-map.js' %}"></script>
  <script src="{% static 'home/js/main.js' %}"></script>
</body>
</html>