products/urls.py
from django.urls import path
from .views import ProductDetailView, ProductView, order, get_started, eportal, it_view, it_success, application_view, it_manual_view, product_success_view

app_name = 'wholphinplus'

urlpatterns = [
    path('', ProductView.as_view(), name='products'),
    path('<int:pk>/', ProductDetailView.as_view(), name='productdetail'),
    path('order/', order, name='order'),
    path('get{}started/', get_started, name='get started'),
    path('eportal/', eportal, name='eportal'),
    path('it1/', it_view, name='it1'),
    path('it1l/', it_manual_view, name='it1l'),
    path('it_success/', it_success, name='it_success'),
    path('application/', application_view, name='application'),
    path('order_success/', product_success_view, name='order_success'),
]

wholphin/urls.py
from django.urls import path
from .views import Home, about, HomePage, CourseHome, services, register_form_vew, CourseDetail, Course_Apply, feedback_view, register_view, contact,terms, register_success

app_name = 'wholphin'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('h/', HomePage.as_view(), name='homepage'),
    path('about/', about, name='about'),
    path('services/', services, name='services'),
    path('courses/', CourseHome.as_view(), name='course'),
    path('<int:pk>/', CourseDetail.as_view(), name='courseprice'),
    path('<int:courses_id>/<int:pk>/', Course_Apply.as_view(), name='apply'),
    path('feedback/', feedback_view, name='feedback'),
    path('contact/', contact, name='contact'),
    path('register/', register_view, name='register'),
    path('t&c/', terms, name='t&c'),
    #path('lay', lay, name='lay'),
    path('register_success/', register_success, name='register_success'),
    path('registered/', register_form_vew, name='registered'),
]

wholphinplus/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from .views import layout, indexs,it, con


urlpatterns = [
    path('ad/', admin.site.urls),
    path('', include('wholphin.urls')),
    path('products/', include('products.urls')),
    path('in/', indexs, name='in'),
    path('it/', it, name='it'),
    path('con/', con, name='con'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Wholphinplus Venture'
admin.site.index_title = 'welcome to who'
admin.site.site_title='wholphin'

products/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
QUALIFICATIONS = (('Choose...', 'Choose...'),('Ssce', 'SSCE'), ('Nd', 'ND'), ('Hnd', 'HND'), ('BSc', 'BSc/BEng'), ('MASTERS', 'Masters'))
JOB_TITLE = (('Choose...', 'Choose...'),('PHPWEB', 'PHP Web Developer'), ('DJANGOWEB', 'Django Web Developer'), ('APP DEVELOPER', 'App Developer'),
             ('SOFTWARE DEVELOPER', 'Software Developer'), ('AI DEVELOPER', 'Artificial Intelligent Engineer'), ('ELECT/ELECT', 'Electrical/Electronic Engineer'),
             ('RECEPTIONIST', 'Receptionist'), ('DATA_SCIENTIST', 'Data Scientist'), ('FRONT_END_DEV.', 'Front End Developer'), ('MACHINE LEARNING ENGR,', 'Machine Learning Engineer'),
             ('PYTHON_DEV', 'Python Developer'))

GENDER = (('Choose...', 'Choose....'), ('MALE', 'Male'), ('FEMALE', 'Female'))
LEVEL = (('Choose...', 'Choose....'), ('300L', '300 Level'), ('400L', '400 Level'), ('Nd', 'ND'), ('Hnd', 'HND'))
DURATION = (('Choose...', 'Choose....'), ('3M', '3 Months'), ('6M', '6 Months'), ('12M', '12 Months'))
STATE = (('Choose...', 'Choose...'),('ab', 'Abia'), ('ada', 'Adamawa'), ('aks', 'Akwa Ibom'), ('bau', 'Bauchi'), ('bay', 'Bayelsa'), ('ben', 'Benue'), ('bor', 'Borno'),
         ('crs', 'Cross River'), ('del', 'Delta'), ('ebo', 'Ebonyi'), ('Ed', 'Edo'), ('Eki', 'Ekiti'), ('Enu', 'Enugu'), ('Gom', 'Gombe'),
         ('Im','Imo'), ('Jiga', 'Jigawa'), ('Kadu', 'Kaduna'), ('Kan', 'Kano'), ('Kat', 'Katsina'), ('Keb', 'Kebbi'), ('Kog', 'Kogi'),
         ('Kwa', 'Kwara'), ('Lag', 'Lagos'), ('Nasa', 'Nasarawa'), ('Nig', 'Niger'), ('Ogu', 'Ogun'), ('Ond', 'Ondo'), ('Osu', 'Osun'),
         ('Oy', 'Oyo'), ('Pla', 'Plateau'), ('Rs', 'Rivers'), ('Sok', 'Sokoto'), ('Tara', 'Taraba'), ('Yob', 'Yobe'),
         ('Zamfa', 'Zamfara'), ('FCT', 'Abuja'))
PRODUCTS = (('Choose...', 'Choose...'), ('AI ECOMMERCE', 'AI Ecommerce Software'), ('AI HEALTH', 'AI Healthcare Software'),
          ('AI FINANCE', 'AI Finance Software'), ('ROBOTIC', 'Robotics'), ('IMAGE RECOG.', 'Image Recognition Software'), ('CHATBOT', 'Chatterbot'),
          ('AI MARKETING', 'AI Marketing Software'), ('RESEARCH', 'Research Project'), ('WEBSITE', 'Responsive Websites'))
from wholphin.models import COURSE
CGPA = (('choose...', 'choose CGPA range...'), ('first class', '4.50 - 5.00'),
        ('second class upper', '3.50 - 4.49'),('second class lower', '2.50 - 3.49'),
        ('others', '1.00 - 2.49'))

class Products(models.Model):
    service_rendered = models.CharField(max_length=100)
    pics = models.ImageField(upload_to='picture')
    description = models.TextField()

    def __str__(self):
        return f'{self.service_rendered}'

    def get_absolute_url(self):
        return reverse('wholphinplus:productdetail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = "Products"


class ProductDetail(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.product} cost {self.price}'

    class Meta:
        verbose_name_plural = "ProductDetail"

    def get_absolute_url(self):
        return reverse('wholphin:productdetail', kwargs={'pk': self.pk})


class OrderNow(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=11)
    email = models.EmailField()
    contact_address = models.CharField(max_length=200)
    date_ordered = models.DateTimeField(auto_now_add=True)
    gender = models.CharField(max_length=20, choices=GENDER)
    state = models.CharField(max_length=30, choices=STATE)
    LGA = models.CharField(max_length=30)
    order = models.CharField(max_length=30, choices=PRODUCTS)

    def __str__(self):
        return f'{self.name} with the email: {self.email} ordered for {self.order} on {self.date_ordered}'

    class Meta:
        verbose_name_plural = "Product Ordered"


class It(models.Model):
    passport = models.ImageField(upload_to='IT', blank=True, null=True)
    full_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=11)
    email = models.EmailField()
    contact_address = models.CharField(max_length=200)
    gender = models.CharField(max_length=20, choices=GENDER)
    state = models.CharField(max_length=30, choices=STATE)
    LGA = models.CharField(max_length=30)
    nationality = models.CharField(max_length=30)
    field_of_internship = models.CharField(max_length=100, choices=COURSE)
    name_of_institude = models.CharField(max_length=100)
    dept = models.CharField(max_length=100)
    faculty = models.CharField(max_length=100)
    level = models.CharField(max_length=30, choices=LEVEL)
    cgpa = models.CharField(max_length=30, choices=CGPA)
    matric_no = models.CharField(max_length=20)
    duration = models.CharField(max_length=20, choices=DURATION)
    date_registered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.full_name} with {self.phone} of {self.name_of_institude} registered for {self.field_of_internship} Internship on {self.date_registered}'

    class Meta:
        verbose_name_plural = "Interns"


class Application(models.Model):
    full_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=11)
    email = models.EmailField()
    contact_address = models.CharField(max_length=200)
    gender = models.CharField(max_length=20, choices=GENDER)
    dob = models.DateField()
    state = models.CharField(max_length=30, choices=STATE)
    LGA = models.CharField(max_length=30)
    educational_qualification = models.CharField(max_length=100, choices=QUALIFICATIONS)
    jod_title = models.CharField(max_length=100, choices=JOB_TITLE)
    # resume = models.FileField(upload_to='Resumes')
    date_registered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.full_name} with {self.phone} of {self.state} state applied as {self.jod_title} on {self.date_registered}'

    class Meta:
        verbose_name_plural = "Job Application"

products/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, DetailView
from .forms import OrderForm, ItForm, ApplicationForm
from products.models import Products


class ProductView(ListView):
    model = Products
    context_object_name = 'products'
    template_name = 'products/products.html'


class ProductDetailView(DetailView):
    model = Products
    context_object_name = 'pro'
    template_name = 'products/productdetail.html'


def order(request):
    form = OrderForm
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('wholphinplus:order_success'))
    return render(request, 'products/order.html', {'form': form})


def get_started(request):
    return render(request, 'products/get_started.html')


def eportal(request):
    return render(request, 'products/eportal.html')


def it_view(request):
    form = ItForm
    if request.method == 'POST':
        form = ItForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('wholphinplus:it1l'))
    return render(request, 'products/it.html', {'form': form})


def it_success(request):
    return render(request, 'products/it_success.html')


def it_manual_view(request):
    m = 'Your IT Application has been received successfully, ensure to print and fill the form below and submit it at the office with the underlisted requirements'
    messages.add_message(request, messages.SUCCESS, m)
    return render(request, 'products/it_manual_form.html')


def application_view(request):
    form = ApplicationForm
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('wholphinplus:it_success'))
    return render(request, 'products/application.html', {'form': form})


def product_success_view(request):
    return render(request, 'products/product_form_success.html')


def order_success(request):
    return render(request, 'products/order_success.html')

products/templates/products/application.html
{% extends 'printingheader.html' %}
{% load static %}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Wholphinplus</title>
 <link rel="stylesheet" href="{% static 'path/to/font-awesome/css/font-awesome.min.css' %}">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>

{% block content %}
<form method="post" action="">
{% csrf_token %}
    <div style="font-family:sans-serif;margin-top:30px" class="container">
<center><h3 style="color:blue"><strong>APPLICATION FORM</strong></h3></center>
  <div class="row text-center" id="top">
     <div class="row text-left" style=" background-color:white;margin-top:20px; display:flex;justify-content:space-around">

       {% for it in form %}
    <div class="col-lg-6 col-md-4 mb-4" >

      <div  class="card text-left"   style="border:1px solid white; display:flex;justify-content:space-around">
<div class="">
          <div class="card-text" style="justify-content:space-around; display:lex-around;padding:10px ">
              <h4>{{it.label_tag}}{{it}}</h4>
</div>

          </div>
      </div>

    </div>
    {% endfor %}

    </div>
</div>
         <input type="submit" value="Apply" class="alert alert-primary">

    </div>
<a href="/" type="submit" class="alert alert"> Back</a>
        </form>

{% endblock %}

products/templates/products/eportal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<center><h1 class="jumbotron">COMING SOON</h1>
<button disabled>OK</button></center>
</body>
</html>

products/templates/products/get_started.html
{% extends 'printingheader.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container" style="margin-top:10px">
     <div class="subheading"><h1 ><strong style="color:blue">Wholphinplus Forms</strong></h1></div>
    <div class="jumbotron" style="width:100%;font-family:Helvetica Neue">
        <h3>Area of Interest</h3><hr style="height:3px;background-color:white">
<div class="row" style=";font-size:20px;padding-left:60px">
    <div class="form-group col-md-12">
       <form class="form-row" method="post" action="{% url 'wholphin:register' %}">
           {% csrf_token %}
           <div >
          <input type="submit" class=" btn btn-primary" style="font-size:13px;color:blue;background:none"   value="Enroll for a Tech Course">
               </div>
        </form>
    </div>


    <div class="form-group col-md-12">
        <form class="form-row" method="post" action="{% url 'wholphinplus:order' %}">
           {% csrf_token %}
           <div >

          <input type="submit" class="btn btn-primary" style="font-size:13px;color:blue;background:none" value="Products: I need a software product/website">
               </div>
        </form>
    </div>


    <div class="form-group col-md-12">
         <form class="form-row" method="post" action="{% url 'wholphinplus:eportal' %}">
           {% csrf_token %}
           <div >

          <input type="submit" class="btn btn-primary" style="font-size:13px;color:blue;background:none"  value="Online Registration: eportal">
               </div>
        </form>


    </div>


    <div class="form-group col-md-12">
         <form class="form-row" method="post" action="{% url 'wholphinplus:it1' %}">
           {% csrf_token %}
           <div >
          <input type="submit" class="btn btn-primary" style="font-size:13px;color:blue;background:none" value="Internship/IT">
               </div>
        </form>

    </div>

    <div class="form-group col-md-12">
         <form class="form-row" method="post" action="{% url 'wholphinplus:application' %}">
           {% csrf_token %}
           <div >

           <input type="submit" class="btn btn-primary" style="font-size:13px;color:blue;background:none"  value="Vacancy: Join Wholphinplus" disabled>
               </div>
        </form>

    </div>

    <div class="form-group col-md-12">
         <form class="form-row" method="post" action="{% url 'wholphin:services' %}">
           {% csrf_token %}
           <div >
           <input type="submit" class=" btn btn-primary" style="font-size:13px;color:blue;background:none"  value="Help with our Tech Services" >
               </div>
        </form>


    </div>

     <div class="form-group col-md-12">
       <form class="form-row" method="post" action="{% url 'wholphinplus:it1' %}">
           {% csrf_token %}
           <div>
                <input type="submit" class=" btn btn-primary" style="font-size:13px;color:blue;background:none"
                       value="Shares: I want to buy shares in wholphinplus" >

               </div>
        </form>
    </div>

</div>
        <a href="/"><button class="btn btn-primary">< Back</button></a>
        </div>
</div>
{% endblock %}
</body>
</html>

products/templates/products/it.html
{% extends 'printingheader.html' %}
{% load static %}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Wholphinplus</title>
 <link rel="stylesheet" href="{% static 'path/to/font-awesome/css/font-awesome.min.css' %}">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>

{% block content %}
<form method="post" action="">
{% csrf_token %}
    <div style="font-family:sans-serif;margin-top:30px" class="container">
<center><h3 style="color:blue"><strong>INTERNSHIP FORM</strong></h3></center>
  <div class="row text-center" id="top">
     <div class="row text-left" style=" background-color:white;margin-top:20px; display:flex;justify-content:space-around">

       {% for it in form %}
    <div class="col-lg-6 col-md-4 mb-4" >

      <div  class="card text-left"   style="border:1px solid white; display:flex;justify-content:space-around">
<div class="">
          <div class="card-text" style="justify-content:space-around; display:lex-around;padding:10px ">
              <h4>{{it.label_tag}}{{it}}</h4>
</div>

          </div>
      </div>

    </div>
    {% endfor %}
    </div>
</div>
         <input type="submit" value="Apply" class="alert alert-primary">

    </div>
<a href="/" type="submit" class="alert alert"> Back</a>
        </form>

{% endblock %}

products/templates/products/it_manual_form.html
{% extends 'printingheader.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
th{border:10px solid black}
    </style>
</head>
<body>
{% block content %}
{% for message in messages %}
<center class="alert alert-primary">
{{message}}
    </center>
{% endfor %}
<iframe src="{% static '_it/IT Form.pdf' %}" style="margin-top:-20px;width:100%;height:100vh"></iframe>
<!--<embed src="{% static '_it/IT Form.pdf' %}" style="width:100vw;height:100vh">-->
{% endblock %}
</body>
</html>

products/templates/products/it_success.html
{% extends 'printingheader.html' %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container">
    <div class="jumbotron" style="margin:20%">
        <center> <div >
          <div >
      <h3 >Your application has been received</h3>
        <h5>We will get back to you as soon as possible</h5>
    </div>
             <a href="/">Back to home</a> || <a href="{% url 'wholphin:course' %}">View our Courses</a>
            </div>
        </center>
        </div>
</div>
{% endblock %}
</body>
</html>

products/templates/products/order.html
{% extends 'printingheader.html' %}
{% load static %}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Wholphinplus</title>
 <link rel="stylesheet" href="{% static 'path/to/font-awesome/css/font-awesome.min.css' %}">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>

{% block content %}
<form method="post" action="">
{% csrf_token %}
    <div style="font-family:sans-serif;margin-top:30px" class="container">
<center><h3 style="color:blue"> Order Form</h3></center>
  <div class="row text-center" id="top">

     <div class="row text-left" style=" background-color:white;margin-top:20px; display:flex;justify-content:space-around">

       {% for order in form %}
    <div class="col-lg-6 col-md-4 mb-4" >

      <div  class="card text-left"   style="border:1px solid white; display:flex;justify-content:space-around">
<div class="">
          <div class="card-text" style="justify-content:space-around; display:lex-around;padding:10px ">
              <h4>{{order.label_tag}}{{order}}</h4>
</div>

          </div>
      </div>

    </div>
    {% endfor %}
    </div>
</div>
         <input type="submit" value="Place Order" class="alert alert-primary">
<a class="alert alert-primary" href="{% url 'wholphinplus:products' %}"><<</a>


    </div>

        </form>
{% endblock %}

products/templates/products/order_success.html
{% extends 'printingheader.html' %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container">
    <div class="jumbotron" style="margin:20%">
        <center> <div >
          <div >
      <h3 >Your application has been received successfully</h3>
        <h5>We will get back to you as soon as possible</h5>
    </div>
             <a href="{% url 'wholphinplus:order' %}">Back</a> || <a href="{% url 'wholphinplus:products' %}">Back to Products</a>
            </div>
        </center>
        </div>
</div>
{% endblock %}
</body>
</html>

products/templates/products/product_form_success.html
{% extends 'printingheader.html' %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container">
    <div class="jumbotron" style="margin:20%">
        <center> <div >
          <div >
      <h3 >Your order has been received successfully</h3>
        <h5>We will get back to you as soon as possible</h5>
    </div>
             <a href="{% url 'wholphinplus:order' %}">Back</a> || <a href="{% url 'wholphinplus:products' %}">View our
        Products</a>
            </div>
        </center>
        </div>
</div>
{% endblock %}
</body>
</html>

products/templates/products/productdetail.html
{% extends 'header.html' %}
{% load static %}
{% block content %}
 <header class="jumbotron my-4" style="font-family:sans-serif;display:flex;justify-content:space-around;height:450px">
    <h4 style="font-family:san-serif;margin-top:50px" class="container-fluid" ><b >{{pro.service_rendered|upper|linebreaks}}</b>
        <p style="font-family:Brush Script MT;font-size:30px">{{pro.description|capfirst|truncatewords:10}}.</p>
        <a href="{% url 'wholphinplus:order' %}" onclick="" class="btn btn-primary">Order Now!</a></h4>

        <div class="img" >
             <img class="card-img-top" src="{{pro.pics.url}}" style="width:100%;height:350px">

      </div>
         </header>


<div class="container" style="font-family:san-serif;">
<!----------SERVICES--->
 {% for price in pro.productdetail_set.all %}

 <h3 style="font-family:san-serif;">{{price.description|linebreaks}}</h3>
     Price: <strike>N</strike>{{price.price}}<br>
 <a class="alert alert-primary" href="{% url 'wholphinplus:products' %}"> < Back </a>
    ||
 <a href="{% url 'wholphinplus:order' %}"><button class="alert alert-primary">Order Now</button></a>

    </div>


      {% endfor %}

{% endblock %}

products/templates/products/products.html
{% extends 'header.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Wholphinplus</title>
<link rel="stylesheet" href="{% static 'path/to/font-awesome/css/font-awesome.min.css' %}">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
{% block content %}
<div class="quote" style="font-family:sans-serif">

     <div class="card-text-center">
         <img class="card-img-top" src="{% static 'image/pro.jpeg' %}" height="500px" width="100%">
          <center><h3 style="margin-top:-330px; color:white" class="container-fluid"><strong>Our Products</strong>
              <br><p style="font-family:san-serif;margin-top:30px;font-size:18px;color:#fff" ><strong>Wholphinplus provides a complete and comprehensive solutions for your unique business need.
        Our IT products are tailored to help you increase productivity and efficiency, providing cutting-edge solutions that
                  scales as your company grows.</strong></p><br>
            <a href="Tel: +2349048178433" class="btn btn-primary" >Call for action!</a></h3>
              </center>
    </div>



</div>
<div class="container py-6">
  <div class="row text-left" style="margin-top:160px; background-color:white; display:flex;justify-content:space-around" id="pro">

   {% for product in products %}
    <div class="col-lg-4 col-md-6 mb-4" >
      <div  class="card text-left"   style="border:01px solid white; display:flex;justify-content:space-around">
    <img class="card-img-top" src="{{product.pics.url}}" height="250rem" width="100px">
          <div class="card-footer">
          <div style="background-color:"><h5 style="color:#add"><a href="{{product.get_absolute_url}}" style="padding-left:0px">
   {{product.service_rendered|capfirst}}</a></h5></div>
          <div class="card-text" style="justify-content:space-around;font-size:20px;font-family:san serif; display:lex-around;padding-left:02px ">
              {% if product.description|wordcount < 4 %}
            {{product.description|truncatewords:20}}
          {% else %}
    {{product.description|truncatewords:10}}


              <div > <a href="{{product.get_absolute_url}}"> Read More!</a></div>

          {% endif %}
          </div>
          </div>
      </div>

    </div>
    {% endfor %}

    </div>

</div>
{% endblock %}
</body>
</html>